# Generated by Django 3.2 on 2023-06-03 12:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('main_img', models.ImageField(blank=True, max_length=256, null=True, upload_to='%Y%m/book/', verbose_name='主图')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传日期')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件类型')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('download_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='下载量')),
                ('favorite_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='收藏量')),
                ('is_public', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否公开')),
                ('is_top', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否为精选图书')),
                ('is_hot', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否为热门图书')),
                ('detail_page_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情页富文本内容')),
            ],
            options={
                'verbose_name': 'PDF书籍',
                'verbose_name_plural': 'PDF书籍',
            },
        ),
    ]
