# Generated by Django 3.2 on 2023-06-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230605_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_type',
            field=models.CharField(blank=True, default='pdf', max_length=50, null=True, verbose_name='文件类型'),
        ),
    ]
