# Generated by Django 3.2 on 2023-06-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='QQ',
            new_name='qq',
        ),
    ]
