# Generated by Django 3.2 on 2023-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('description', models.TextField(verbose_name='描述')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('tags', models.CharField(max_length=255, verbose_name='标签')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载量')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='收藏量')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('detail_page_content', models.TextField(verbose_name='详情页富文本内容')),
            ],
            options={
                'verbose_name': 'PDF书籍',
                'verbose_name_plural': 'PDF书籍',
            },
        ),
    ]
