# Generated by Django 3.2 on 2023-06-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20230602_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFBook',
            new_name='Book',
        ),
    ]
