# Generated by Django 3.2 on 2023-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_pdfbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_img',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='%Y%m/book/', verbose_name='主图'),
        ),
    ]
