# Generated by Django 3.2 on 2023-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_hot',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='热门图书'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_top',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='精选图书'),
        ),
    ]
